TrainingArguments:
  num_train_epochs: 1
  warmup_steps: 500
  per_device_train_batch_size: 1
  weight_decay: 0.01
  logging_steps: 10
  eval_strategy: steps
  eval_steps: 500
  save_steps: 1e6
  gradient_accumulation_steps: 16
  per_device_eval_batch_size: 32
  greater_is_better: False
  load_best_model_at_end: True
  metric_for_best_model: eval_loss